import type { Row } from "../types";

/** A single parameterised statement. Values are never interpolated into `sql`. */
export interface Statement {
  sql: string;
  values: unknown[];
}

/** Column name -> Postgres data type, as a snapshot records it. */
export type ColumnTypes = Record<string, string>;

export function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

export function qualify(table: string): string {
  return `${quoteIdent("public")}.${quoteIdent(table)}`;
}

/**
 * Turn a value from a snapshot document back into something pg can bind.
 *
 * Most types need nothing: numeric and bigint are already the strings pg
 * returned, and date/timestamp/timestamptz are ISO forms Postgres parses back
 * to the same value. Two need help:
 *
 * - bytea, which JSON.stringify turns into {"type":"Buffer","data":[...]}.
 * - json and jsonb, because node-postgres renders a JS array as a Postgres
 *   array literal. A jsonb value of [1,2,3] would go to the server as {1,2,3}
 *   and the insert would fail, so JSON documents are stringified explicitly.
 */
export function encodeValue(value: unknown, dataType: string | undefined): unknown {
  if (value === null || value === undefined) return null;

  if (dataType === "json" || dataType === "jsonb") return JSON.stringify(value);

  if (dataType === "bytea") {
    if (Buffer.isBuffer(value)) return value;
    if (isSerialisedBuffer(value)) return Buffer.from(value.data);
  }

  return value;
}

function isSerialisedBuffer(value: unknown): value is { type: "Buffer"; data: number[] } {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as { type?: unknown }).type === "Buffer" &&
    Array.isArray((value as { data?: unknown }).data)
  );
}

export function insertStatement(
  table: string,
  row: Row,
  columns: ColumnTypes,
  identityAlways: ReadonlySet<string>,
): Statement {
  const names = Object.keys(row);
  const values = names.map((name) => encodeValue(row[name], columns[name]));
  const placeholders = names.map((_, index) => `$${index + 1}`);

  // GENERATED ALWAYS AS IDENTITY refuses an explicit value without this.
  // GENERATED BY DEFAULT accepts one, and does not get the override.
  const overriding = names.some((name) => identityAlways.has(name)) ? " OVERRIDING SYSTEM VALUE" : "";

  return {
    sql:
      `INSERT INTO ${qualify(table)} (${names.map(quoteIdent).join(", ")})` +
      `${overriding} VALUES (${placeholders.join(", ")})`,
    values,
  };
}

export function updateStatement(table: string, key: Row, after: Row, columns: ColumnTypes): Statement {
  const values: unknown[] = [];

  const assignments = Object.keys(after).map((name) => {
    values.push(encodeValue(after[name], columns[name]));
    return `${quoteIdent(name)} = $${values.length}`;
  });

  return {
    sql: `UPDATE ${qualify(table)} SET ${assignments.join(", ")} WHERE ${whereKey(key, columns, values)}`,
    values,
  };
}

export function deleteStatement(table: string, key: Row, columns: ColumnTypes): Statement {
  const values: unknown[] = [];
  return {
    sql: `DELETE FROM ${qualify(table)} WHERE ${whereKey(key, columns, values)}`,
    values,
  };
}

/** Empty a table completely. Used for tables with no primary key. */
export function deleteAllStatement(table: string): Statement {
  return { sql: `DELETE FROM ${qualify(table)}`, values: [] };
}

/**
 * Drag a sequence back up past the rows just inserted with explicit keys.
 *
 * The third argument to setval is what makes this correct on an empty table:
 * with rows it is true, so the next value is max + 1; with no rows it is false,
 * so the next value is 1. Passing a bare NULL to setval would error, which is
 * why COALESCE alone is not enough.
 */
export function resyncSequenceStatement(table: string, column: string, sequence: string): Statement {
  const col = quoteIdent(column);
  return {
    sql: `SELECT setval($1, COALESCE(MAX(${col}), 1), MAX(${col}) IS NOT NULL) FROM ${qualify(table)}`,
    values: [sequence],
  };
}

/** Primary key columns are never null, so plain equality is enough. */
function whereKey(key: Row, columns: ColumnTypes, values: unknown[]): string {
  return Object.keys(key)
    .map((name) => {
      values.push(encodeValue(key[name], columns[name]));
      return `${quoteIdent(name)} = $${values.length}`;
    })
    .join(" AND ");
}
